// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { RateLimiter, RATE_LIMITS } from '@/utils/rateLimiter';

const SUPABASE_URL = "https://xhrievvdnajvylyrowwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhocmlldnZkbmFqdnlseXJvd3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ1MzUsImV4cCI6MjA2NTQ3MDUzNX0.RfwNUnsTFAzfRqxiqCOtunXBTMJj90MKWOm1iwzVBAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Optimize token refresh settings to reduce rate limiting
    detectSessionInUrl: true,
    // Add custom refresh throttling
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'random-app@1.0.0'
    }
  }
});

// Session management without problematic cache
supabase.auth.onAuthStateChange((event) => {
  if (event === 'SIGNED_IN') {
    // Reset rate limiter on successful sign in
    RateLimiter.reset('supabase_session_check');
  }
});